name: Run Selenium Tests

on: [push, pull_request]

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium

      - name: Start Flask app in background
        run: |
          nohup python youface.py > flask.log 2>&1 &
          sleep 5

      - name: Run Selenium tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          python selenium_example.py
